language: go

go:
  - "1.11.x"

sudo: required

env:
  - GO111MODULE=on

services:
  - docker

install:
  - docker build -f docker/dev.Dockerfile -t ethereum/sharding-p2p:latest .
  - docker run -d --name p2p ethereum/sharding-p2p:latest

before_install:
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get update
  - sudo apt-get install -y python3.6
  - go mod download

script:
  - go test -v ./...
  - ./cli-example/iterate_all_rpc_call.sh
  - docker ps | grep -q p2p
