language: go

sudo: false

go:
  - "1.10.x"

sudo: required

services:
  - docker

install:
  - docker build -t ethereum/sharding-p2p:latest .
  - docker run -d --name p2p ethereum/sharding-p2p:latest
  - make deps

before_install:
  - go get github.com/ethresearch/sharding-p2p-poc

script:
  - go test -v ./...
  - docker ps | grep -q p2p
