language: go

sudo: false

go:
  - "1.10.x"

sudo: required

services:
  - docker

install:
  - docker build -f docker/prod.Dockerfile -t ethereum/sharding-p2p:latest .
  - docker run -d --name p2p ethereum/sharding-p2p:latest
  - make deps

before_install:
  - go get ./...

script:
  - go test -v ./...
  - docker ps | grep -q p2p
