version: '3'
services:
  bootstrap:
    image: ethereum/sharding-p2p:dev
    ports:
      - "5566"
      - "7788"
    networks:
      - sharding-p2p
    volumes:
      - ../main:/main
    command: /main -seed=0 -port=5566 -rpcport=7788
  node:
    image: ethereum/sharding-p2p:dev
    ports:
      - "5566"
      - "7788"
    networks:
      - sharding-p2p
    volumes:
      - ./cmd/run.sh:/run.sh
      - ../main:/main
    command: ["sh", "/run.sh"]
networks:
  sharding-p2p:

