---
- name: Git clone sharding-p2p-poc
  git:
    repo: 'https://github.com/ethresearch/sharding-p2p-poc.git'
    dest: "/home/ubuntu/sharding-p2p-poc"
    version: master
    accept_hostkey: true
    update: true

- name: Build docker image
  become: true
  docker_image:
    path: "/home/ubuntu/sharding-p2p-poc"
    name: ethereum/sharding-p2p:dev
    dockerfile: docker/dev.Dockerfile
    nocache: true
    force: true
    rm: true
    push: false

- name: Start docker containers
  become: true
  docker_container:
    name: peer_{{ item }}
    image: ethereum/sharding-p2p:dev
    state: started
    restart_policy: always
    memory: 4g
    privileged: true
    published_ports:
      - "{{ item }}:{{ item }}"
      - "{{ 100 + item|int }}:{{ 100 + item|int }}"
    command: [
      "sh -c \"./sharding-p2p-poc -loglevel=DEBUG -ip=0.0.0.0 -seed={{ item }}\""
    ]
  with_sequence: end="{{ p2p_nodes_end }}" start="{{ p2p_nodes_start }}"