---
- name: Start docker containers
  become: true
  docker_container:
    name: peer_{{ item }}
    image: ethereum/sharding-p2p:dev
    state: started
    restart_policy: always
    memory: 4g
    privileged: true
    published_ports:
      - "{{ item }}:10000" # listen port
      - "{{ 100 + item|int }}:13000" # RPC port
    command: [
      "sh -c \"./sharding-p2p-poc -loglevel=DEBUG -ip=0.0.0.0 -seed={{ item }}\""
    ]
  with_sequence: end="{{ p2p_nodes_end }}" start="{{ p2p_nodes_start }}"