---

- name: setup servers
  hosts: nodes
  become: true
  gather_facts: False
  roles:
    - role: python
    - role: docker
  tasks:
  - include_role:
      name: common
      tasks_from: build_image

- name: Create topology
  hosts: localhost
  tasks:
  - command: python scripts/topology.py hosts


- name: add peers
  hosts: nodes
  gather_facts: false
  vars_files:
    - group_vars/all/topology.yml
  tasks:
  - include_role:
      name: common
      tasks_from: cli_addpeer


- name: spin up servers
  hosts: nodes
  roles:
    - role: node

- name: assume everyone is a proposer
  hosts: nodes
  roles:
    - role: proposer
