---

- name: setup servers
  hosts: nodes
  become: true
  gather_facts: False
  roles:
    - role: python
    - role: docker


- name: spin up servers
  hosts: nodes
  roles:
    - role: node

- name: assume everyone is a proposer
  hosts: nodes
  roles:
    - role: proposer
